### ISSUE TITLE
executable named script

### ISSUE THREAD

**Issue by dpritchett** [bradmontgomery/python-ninethreesix#3]
## Problem

```
$ ninethreesix
ninethreesix: command not found
```
## Solution

https://github.com/ansible/ansible/blob/e6e69c089414835d448bbffffd21c4775f2b23f0/setup.py#L30-L36

**Comment by bradmontgomery** [comment]
:+1:

**Comment by bradmontgomery** [comment]
Added in #6.  👋 @dpritchett

**Comment by dpritchett** [comment]
Hi @bradmontgomery! Glad to see the fix landed. Hope all is well up in Memphis 😃
